ALTER TABLE `operox`.`OFFER_COUPONS` 
CHANGE COLUMN `INVOICE_AMOUNT` `INVOICE_AMOUNT` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `COUPON_VALUE` `COUPON_VALUE` FLOAT NULL DEFAULT NULL ;

ALTER TABLE `operox`.`PAYMENT_DETAILS` 
CHANGE COLUMN `COUPON2_AMOUNT` `COUPON2_AMOUNT` FLOAT NULL DEFAULT NULL ;
