
DROP TABLE IF EXISTS `operox`.`CURRENCY`;
CREATE TABLE `operox`.`CURRENCY` (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  COMPANY_ID BIGINT,
  CURRENCY VARCHAR(50),
  SYMBOL  VARCHAR(50),
  EXCHANGE_VALUE VARCHAR(50),
  IS_DEFAULT VARCHAR(5), 
  DESCRIPTION TEXT,
  STATUS INT,
  CREATED_DATE DATE,
  CREATED_BY VARCHAR(10),
  UPDATED_DATE DATE,
  UPDATED_BY VARCHAR(10),
  FOREIGN KEY(COMPANY_ID) REFERENCES `operox`.`COMPANY`(ID),
  PRIMARY KEY (`ID`) 
); 