
INSERT INTO `operox`.`TAX` (`TAX_NAME`, `TAX_VALUE`, `STORE_ID`) VALUES ('payroll', '30', '1');

ALTER TABLE `operox`.`PAYROLL` 
ADD COLUMN `NET_PAY` VARCHAR(45) NULL AFTER `LOP`,
ADD COLUMN `FROM_DATE` DATE NULL AFTER `NET_PAY`,
ADD COLUMN `TO_DATE` DATE NULL AFTER `FROM_DATE`;

ALTER TABLE `operox`.`TAX` 
ADD COLUMN `USER_ID` BIGINT NULL AFTER `ID`;