ALTER TABLE `operox`.`OFFER_DISCOUNT_ON_INVOICE` 
CHANGE COLUMN `INOVICE_AMOUNT` `INOVICE_AMOUNT` FLOAT NULL DEFAULT NULL ,
CHANGE COLUMN `DISCOUNT_AMOUNT` `DISCOUNT_AMOUNT` FLOAT NULL DEFAULT NULL ;
