ALTER TABLE `operox`.`WORK_ORDER_RESOURCE_MANAGEMENT` 
ADD COLUMN `TYPE` VARCHAR(45) NULL AFTER `STATUS`;

ALTER TABLE `operox`.`USER` 
ADD COLUMN `GENDER` VARCHAR(45) NULL AFTER `PAYSLIP_TO_DATE`;

INSERT INTO `operox`.`ROLE` (`ID`, `ROLE_NAME`, `DISPLAY_NAME`) VALUES ('8', 'ROLE_CUSTOMER', 'CUSTOMER');