DROP TABLE IF EXISTS `operox`.`MEASURING_UNIT`;
CREATE TABLE `operox`.`MEASURING_UNIT` (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  MEASURING_UNIT VARCHAR(500) DEFAULT NULL,
  DESCRIPTION VARCHAR(500) DEFAULT NULL,
  CREATED_DATE DATE,
  CREATED_BY VARCHAR(10),
  UPDATED_DATE DATE,
  UPDATED_BY VARCHAR(10),
  PRIMARY KEY (`ID`) 
); 


ALTER TABLE `operox`.`CATEGORY`
	ADD COLUMN `DESCRIPTION` VARCHAR(250) NULL AFTER `UPDATED_BY`;
	
ALTER TABLE `operox`.`BRAND`
	ADD COLUMN `DESCRIPTION` VARCHAR(250) NULL AFTER `CATEGORY_ID`;
