
CALL operox.AlterTableAddColumn ('operox','OFFER','OFFER_NAME','VARCHAR(250) NULL AFTER `ID`');
CALL operox.AlterTableAddColumn ('operox','OFFER','OFFER_START_DATE','DATE NULL AFTER `OFFER_TYPE`');
CALL operox.AlterTableAddColumn ('operox','OFFER','OFFER_END_DATE','DATE NULL AFTER `OFFER_START_DATE`');
CALL operox.AlterTableAddColumn ('operox','OFFER','OFFER_START_TIME','VARCHAR(10) NULL AFTER `OFFER_END_DATE`');
CALL operox.AlterTableAddColumn ('operox','OFFER','OFFER_END_TIME','VARCHAR(10) NULL AFTER `OFFER_START_TIME`');

CALL operox.AlterTableAddColumn ('operox','OFFER','SUNDAY','VARCHAR(2) NULL AFTER `OFFER_END_TIME`');
CALL operox.AlterTableAddColumn ('operox','OFFER','MONDAY','VARCHAR(2) NULL AFTER `SUNDAY`');
CALL operox.AlterTableAddColumn ('operox','OFFER','TUESDAY','VARCHAR(2) NULL AFTER `MONDAY`');
CALL operox.AlterTableAddColumn ('operox','OFFER','WEDNESDAY','VARCHAR(2) NULL AFTER `TUESDAY`');
CALL operox.AlterTableAddColumn ('operox','OFFER','THURSDAY','VARCHAR(2) NULL AFTER `WEDNESDAY`');
CALL operox.AlterTableAddColumn ('operox','OFFER','FRIDAY','VARCHAR(2) NULL AFTER `THURSDAY`');
CALL operox.AlterTableAddColumn ('operox','OFFER','SATURDAY','VARCHAR(2) NULL AFTER `FRIDAY`');

CALL operox.AlterTableAddColumn ('operox','OFFER','STATUS','INT NULL AFTER `SATURDAY`');
CALL operox.AlterTableAddColumn ('operox','OFFER','CREATED_DATE','DATE NULL AFTER `STATUS`');
CALL operox.AlterTableAddColumn ('operox','OFFER','CREATED_BY','VARCHAR(20) NULL AFTER `CREATED_DATE`');
CALL operox.AlterTableAddColumn ('operox','OFFER','UPDATED_DATE','DATE NULL AFTER `CREATED_BY`');
CALL operox.AlterTableAddColumn ('operox','OFFER','UPDATED_BY','VARCHAR(20) NULL AFTER `UPDATED_DATE`');



DROP TABLE IF EXISTS `operox`.`OFFER_BUYXGETY`;
CREATE TABLE `operox`.`OFFER_BUYXGETY` (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  OFFER_ID BIGINT,
  BUY_ITEM VARCHAR(500) DEFAULT NULL,
  BUY_ITEM_QUANTITY VARCHAR(50) DEFAULT NULL,
  FREE_ITEM VARCHAR(500) DEFAULT NULL,
  FREE_ITEM_QUANTITY VARCHAR(50) DEFAULT NULL,
  STATUS INT,
  CREATED_DATE DATE ,
  CREATED_BY VARCHAR(10) DEFAULT NULL,
  UPDATED_DATE DATE,
  UPDATED_BY VARCHAR(10) DEFAULT NULL,
  FOREIGN KEY(OFFER_ID) REFERENCES `operox`.`OFFER`(ID),
  PRIMARY KEY (`ID`) 
); 



DROP TABLE IF EXISTS `operox`.`OFFER_DISCOUNT_ON_INVOICE`;
CREATE TABLE `operox`.`OFFER_DISCOUNT_ON_INVOICE` (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  OFFER_ID BIGINT,
  SL_NO INT DEFAULT NULL,
  INOVICE_AMOUNT VARCHAR(50) DEFAULT NULL,
  DISCOUNT_AMOUNT VARCHAR(50) DEFAULT NULL,
  IS_PERCENTAGE VARCHAR(2) DEFAULT NULL,
  STATUS INT,
  CREATED_DATE DATE,
  CREATED_BY VARCHAR(10) DEFAULT NULL,
  UPDATED_DATE DATE,
  UPDATED_BY VARCHAR(10) DEFAULT NULL,
  FOREIGN KEY(OFFER_ID) REFERENCES `operox`.`OFFER`(ID),
  PRIMARY KEY (`ID`) 
); 



DROP TABLE IF EXISTS `operox`.`OFFER_DISCOUNT_ON_ITEM`;
CREATE TABLE `operox`.`OFFER_DISCOUNT_ON_ITEM` (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  OFFER_ID BIGINT,
  SL_NO INT DEFAULT NULL,
  BAR_CODE VARCHAR(500) DEFAULT NULL,
  ITEM_NAME VARCHAR(500) DEFAULT NULL,
  QUANTITY INT DEFAULT NULL,
  DISCOUNT VARCHAR(10) DEFAULT NULL,
  IS_PERCENTAGE VARCHAR(2) DEFAULT NULL,
  STATUS INT,
  CREATED_DATE DATE,
  CREATED_BY VARCHAR(10) DEFAULT NULL,
  UPDATED_DATE DATE,
  UPDATED_BY VARCHAR(10) DEFAULT NULL,
  FOREIGN KEY(OFFER_ID) REFERENCES `operox`.`OFFER`(ID),
  PRIMARY KEY (`ID`) 
); 


DROP TABLE IF EXISTS `operox`.`OFFER_FREE_ITEM_ON_INVOICE`;
CREATE TABLE `operox`.`OFFER_FREE_ITEM_ON_INVOICE` (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  OFFER_ID BIGINT,
  TOTAL_INVOICE_AMOUNT VARCHAR(10) DEFAULT NULL,
  FREE_ITEM VARCHAR(500) DEFAULT NULL,
  FREE_ITEM_QUANTITY VARCHAR(50) DEFAULT NULL,
  STATUS INT,
  CREATED_DATE DATE,
  CREATED_BY VARCHAR(10) DEFAULT NULL,
  UPDATED_DATE DATE,
  UPDATED_BY VARCHAR(10) DEFAULT NULL,
  FOREIGN KEY(OFFER_ID) REFERENCES `operox`.`OFFER`(ID),
  PRIMARY KEY (`ID`) 
); 


DROP TABLE IF EXISTS `operox`.`OFFER_COUPONS`;
CREATE TABLE `operox`.`OFFER_COUPONS` (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  OFFER_ID BIGINT,
  COUPON_NAME VARCHAR(500) DEFAULT NULL,
  INVOICE_AMOUNT VARCHAR(20) DEFAULT NULL,
  COUPON_VALUE VARCHAR(20) DEFAULT NULL,
  STATUS INT,
  CREATED_DATE DATE,
  CREATED_BY VARCHAR(10) DEFAULT NULL,
  UPDATED_DATE DATE,
  UPDATED_BY VARCHAR(10) DEFAULT NULL,
  FOREIGN KEY(OFFER_ID) REFERENCES `operox`.`OFFER`(ID),
  PRIMARY KEY (`ID`) 
); 



DROP TABLE IF EXISTS `operox`.`OFFER_LOYALTY_POINTS`;
CREATE TABLE `operox`.`OFFER_LOYALTY_POINTS` (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  OFFER_ID BIGINT,
  INVOICE_AMOUNT VARCHAR(20) DEFAULT NULL,
  LOYALTY_POINTS VARCHAR(20) DEFAULT NULL,
  LOYALTY_POINT_VALUE VARCHAR(20) DEFAULT NULL,
  STATUS INT,
  CREATED_DATE DATE,
  CREATED_BY VARCHAR(10) DEFAULT NULL,
  UPDATED_DATE DATE,
  UPDATED_BY VARCHAR(10) DEFAULT NULL,
  FOREIGN KEY(OFFER_ID) REFERENCES `operox`.`OFFER`(ID),
  PRIMARY KEY (`ID`) 
); 



DROP TABLE IF EXISTS `operox`.`OFFER_STORES`;
CREATE TABLE `operox`.`OFFER_STORES` (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  OFFER_ID BIGINT,
  STORE_ID BIGINT,
  STATUS INT,
  CREATED_DATE DATE,
  CREATED_BY VARCHAR(10) DEFAULT NULL,
  UPDATED_DATE DATE,
  UPDATED_BY VARCHAR(10) DEFAULT NULL,
  FOREIGN KEY(OFFER_ID) REFERENCES `operox`.`OFFER`(ID),
  FOREIGN KEY(STORE_ID) REFERENCES `operox`.`STORE`(ID),
  PRIMARY KEY (`ID`) 
); 


DROP TABLE IF EXISTS `operox`.`OFFER_CUSTOMER_LEVEL`;
CREATE TABLE `operox`.`OFFER_CUSTOMER_LEVEL` (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  OFFER_ID BIGINT,
  CUSTOMER_LEVEL VARCHAR(20) DEFAULT NULL,
  STATUS INT,
  CREATED_DATE DATE,
  CREATED_BY VARCHAR(10) DEFAULT NULL,
  UPDATED_DATE DATE,
  UPDATED_BY VARCHAR(10) DEFAULT NULL,
  FOREIGN KEY(OFFER_ID) REFERENCES `operox`.`OFFER`(ID),
  PRIMARY KEY (`ID`) 
); 

