ALTER TABLE `operox`.`SUPPLIER` ADD COLUMN `TIN` INT(50) NULL DEFAULT NULL  AFTER `STATUS` ;

DROP TABLE IF EXISTS `operox`.`DISCOUNT`;
CREATE TABLE `operox`.`DISCOUNT` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `DISCOUNT_NAME` VARCHAR(500) NULL,
  `DISCOUNT_VALUE` VARCHAR(500) NULL,
  `STORE_ID` BIGINT(20) NULL,
  `STATUS` INT(11) NULL,
  `CREATED_DATE` DATE NULL,
  `CREATED_BY` VARCHAR(10) NULL,
  `UPDATED_DATE` DATE NULL,
  `UPDATED_BY` VARCHAR(10) NULL,
  PRIMARY KEY (`ID`));
  
  
CALL operox.AlterTableAddColumn ('operox','PRODUCT_STOCK','DISCOUNT_ID','BIGINT NULL AFTER `TAX_ID`');
ALTER TABLE `operox`.`PRODUCT_STOCK`  ADD FOREIGN KEY(DISCOUNT_ID) REFERENCES DISCOUNT(ID);