DROP TABLE IF EXISTS `operox`.`USER_ECOMM_ORDER`;
CREATE TABLE `operox`.`USER_ECOMM_ORDER` (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  USER_ID BIGINT,
  PRODUCT_ID BIGINT,
  PRODUCT_STOCK_ID BIGINT,
  STATUS INT,
  ORDER_STATUS VARCHAR(20) DEFAULT NULL,
  CREATED_DATE DATE,
  CREATED_BY VARCHAR(10),
  UPDATED_DATE DATE,
  UPDATED_BY VARCHAR(10),
  FOREIGN KEY(USER_ID) REFERENCES `operox`.`USER`(ID),
  FOREIGN KEY(PRODUCT_ID) REFERENCES `operox`.`PRODUCT`(ID),
  FOREIGN KEY(PRODUCT_STOCK_ID) REFERENCES `operox`.`PRODUCT_STOCK`(ID),
  PRIMARY KEY (`ID`) 
); 
