
ALTER TABLE `operox`.`RAW_MATERIAL` DROP COLUMN `MEASURING_UNIT` ;

CALL operox.AlterTableAddColumn ('operox','RAW_MATERIAL','MEASURING_UNIT_ID','BIGINT NULL AFTER `ID`');
ALTER TABLE `operox`.`RAW_MATERIAL` ADD FOREIGN KEY(MEASURING_UNIT_ID) REFERENCES MEASURING_UNIT(ID);

