ALTER TABLE `operox`.`QC_CHECK_LIST`
	ADD COLUMN `FILE_CONTENT_TYPE` VARCHAR(50) NULL AFTER `UPDATED_BY`,
	ADD COLUMN `FILE_NAME` TEXT NULL AFTER `FILE_CONTENT_TYPE`,
	ADD COLUMN `DOC_FILE` MEDIUMBLOB NULL AFTER `FILE_NAME`,
	ADD COLUMN `DESCRIPTION` VARCHAR(250) NULL AFTER `DOC_FILE`,
	ADD COLUMN `CHECK_NAME` VARCHAR(250) NULL AFTER `DESCRIPTION`; 
	
CALL operox.AlterTableAddColumn ('operox','QC_CHECK_LIST','STORE_ID','BIGINT NULL AFTER `ID`');
ALTER TABLE `operox`.`QC_CHECK_LIST` ADD FOREIGN KEY(STORE_ID) REFERENCES STORE(ID);

ALTER TABLE `operox`.`QC_CHECK_LIST_REPORT`
	ADD COLUMN `HOW_TO_CHECK` TEXT NULL AFTER `UPDATED_BY`,
	ADD COLUMN `WHAT_TO_CHECK` TEXT NULL AFTER `HOW_TO_CHECK`;
	
	ALTER TABLE `operox`.`QC_CHECK_LIST_REPORT`
	ADD COLUMN `TEST_DESCRIPTION` TEXT NULL AFTER `WHAT_TO_CHECK`;
	
CALL operox.AlterTableAddColumn ('operox','QC_CHECK_LIST','PRODUCT_ID','BIGINT NULL AFTER `ID`');
ALTER TABLE `operox`.`QC_CHECK_LIST` ADD FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(ID);
