CALL operox.AlterTableAddColumn ('operox','RECEIVED_STOCK','SUBMISSION_STATUS','VARCHAR(25) NULL AFTER `POD_NUMBER`');

CALL operox.AlterTableAddColumn ('operox','STOCK_RETURNS_ITEMS','STOCK_RETURNS_ID','BIGINT NULL AFTER `BATCH_ID`');
ALTER TABLE `operox`.`STOCK_RETURNS_ITEMS`  ADD FOREIGN KEY(STOCK_RETURNS_ID) REFERENCES STOCK_RETURNS(ID);

CALL operox.AlterTableAddColumn ('operox','STOCK_RETURNS','TRANSFER_NUMBER','VARCHAR(50) NULL AFTER `RETURN_TO`');

CALL operox.AlterTableAddColumn ('operox','PURCHASE_ORDER','SUBMISSION_STATUS','VARCHAR(25) NULL AFTER `STATUS`');

CALL operox.AlterTableAddColumn ('operox','STOCK_RETURNS','SUBMISSION_STATUS','VARCHAR(25) NULL AFTER `TRANSFER_NUMBER`');


CALL operox.AlterTableAddColumn ('operox','SUPPLIER_INVOICES','SUPPLIER_INVOICE_NUMBER','VARCHAR(25) NULL AFTER `STORE_ID`');

CALL operox.AlterTableAddColumn ('operox','SUPPLIER_INVOICES','STOCK_RECEIVED_ID','BIGINT NULL AFTER `SUPPLIER_ID`');
ALTER TABLE `operox`.`SUPPLIER_INVOICES`  ADD FOREIGN KEY(STOCK_RECEIVED_ID) REFERENCES RECEIVED_STOCK(ID);


CALL operox.AlterTableAddColumn ('operox','STOCK_RETURNS','TOTAL_AMOUNT','VARCHAR(25) NULL AFTER `TRANSFER_NUMBER`');
CALL operox.AlterTableAddColumn ('operox','STOCK_RETURNS','TOTAL_NUMBEROF_PRODUCTS','VARCHAR(25) NULL AFTER `TOTAL_AMOUNT`');
CALL operox.AlterTableAddColumn ('operox','STOCK_RETURNS','COMMENT','TEXT DEFAULT NULL AFTER `TOTAL_NUMBEROF_PRODUCTS`');

CALL operox.AlterTableAddColumn ('operox','STOCK_RETURNS','STOCK_RETURN_BY','BIGINT NULL AFTER `TRANSFER_NUMBER`');
ALTER TABLE `operox`.`STOCK_RETURNS`  ADD FOREIGN KEY(STOCK_RETURN_BY) REFERENCES `USER`(ID);


