
ALTER TABLE `operox`.`CUSTOMER` 
CHANGE COLUMN `UPDATED_BY` `UPDATED_BY` VARCHAR(45) NULL DEFAULT NULL ;

CALL operox.AlterTableAddColumn ('operox','RECEIVED_STOCK_ITEMS','PRODUCT_PRICE','VARCHAR(25) NULL AFTER `QUANTITY`');
CALL operox.AlterTableAddColumn ('operox','RECEIVED_STOCK_ITEMS','DISCOUNT','VARCHAR(25) NULL AFTER`PRODUCT_PRICE`');
CALL operox.AlterTableAddColumn ('operox','RECEIVED_STOCK_ITEMS','TAX','VARCHAR(25) NULL AFTER `DISCOUNT`');
CALL operox.AlterTableAddColumn ('operox','RECEIVED_STOCK_ITEMS','MRP','VARCHAR(25) NULL AFTER `TAX`');
     
CALL operox.AlterTableAddColumn ('operox','STOCK_RETURNS_ITEMS','BARCODE','VARCHAR(25) NULL AFTER `STATUS`');
CALL operox.AlterTableAddColumn ('operox','STOCK_RETURNS_ITEMS','AMOUNT','VARCHAR(25) NULL AFTER `BARCODE`');

CALL operox.AlterTableAddColumn ('operox','STOCK_RETURNS','TRANSFER_DATE','DATE  AFTER `STATUS`');
CALL operox.AlterTableAddColumn ('operox','STOCK_RETURNS','RECEVED_DATE','DATE  AFTER `TRANSFER_DATE`');

    
    

CALL AlterTableRemoveColumn('operox','RECEIVED_STOCK','POD_NUMBER');

CALL operox.AlterTableAddColumn ('operox','RECEIVED_STOCK','POD_NUMBER','BIGINT NULL AFTER `STATUS`');
ALTER TABLE `operox`.`RECEIVED_STOCK`  ADD FOREIGN KEY(POD_NUMBER) REFERENCES PURCHASE_ORDER(ID);

CALL operox.AlterTableAddColumn ('operox','PURCHASE_ORDER','PURCHASE_NUMBER','VARCHAR(50) NULL AFTER `STATUS`');
    


CALL operox.AlterTableAddColumn ('operox','STOCK_RETURNS_ITEMS','MANUFACTUREDATE','DATE  AFTER `STATUS`');
CALL operox.AlterTableAddColumn ('operox','STOCK_RETURNS_ITEMS','EXPERIEDATE','DATE  AFTER `MANUFACTUREDATE`');    
CALL operox.AlterTableAddColumn ('operox','STOCK_RETURNS_ITEMS','PRODUCT_PRICE','VARCHAR(25) NULL AFTER `PRODUCT_ID`');    
CALL operox.AlterTableAddColumn ('operox','STOCK_RETURNS_ITEMS','BATCH_ID','VARCHAR(100) NULL AFTER `PRODUCT_PRICE`');  

