DROP TABLE IF EXISTS `operox`.`PASSWORD_RESETS`;
CREATE TABLE `operox`.`PASSWORD_RESETS` (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  USER_ID BIGINT,
  EMAIL VARCHAR(100) DEFAULT NULL,
  VERIFICATION_CODE VARCHAR(20) DEFAULT NULL,
  RESET_STATUS VARCHAR(20),
  STATUS INT,
  CREATED_DATE DATE,
  CREATED_BY VARCHAR(10),
  UPDATED_DATE DATE,
  UPDATED_BY VARCHAR(10),
  PRIMARY KEY (`ID`),
  FOREIGN KEY(USER_ID) REFERENCES `operox`.`USER`(ID)
) ;