ALTER TABLE `operox`.`PRODUCT` DROP COLUMN `MEASURING_UNIT` ;

CALL operox.AlterTableAddColumn ('operox','PRODUCT','MEASURING_UNIT_ID','BIGINT NULL AFTER `ID`');
ALTER TABLE `operox`.`PRODUCT` ADD FOREIGN KEY(MEASURING_UNIT_ID) REFERENCES MEASURING_UNIT(ID);