ALTER TABLE `operox`.`QC_EXECUTION`
	ADD COLUMN `QC_STATUS` VARCHAR(10) NULL DEFAULT NULL AFTER `UPDATED_BY`;
	
CALL operox.AlterTableAddColumn ('operox','QC_EXECUTION','WORK_ORDER_ID','BIGINT NULL AFTER `ID`');
ALTER TABLE `operox`.`QC_EXECUTION` ADD FOREIGN KEY(WORK_ORDER_ID) REFERENCES WORK_ORDER(ID);

CALL operox.AlterTableAddColumn ('operox','QC_EXECUTION_RESULTS','QC_EXECUTION_ID','BIGINT NULL AFTER `ID`');
ALTER TABLE `operox`.`QC_EXECUTION_RESULTS` ADD FOREIGN KEY(QC_EXECUTION_ID) REFERENCES QC_EXECUTION(ID);

ALTER TABLE `operox`.`QC_EXECUTION`
ADD COLUMN `QC_EXECUTION_TYPE` VARCHAR(50) NULL AFTER `STATUS`;
