DROP TABLE IF EXISTS `operox`.`PAYMENT_DETAILS`;
CREATE TABLE `operox`.`PAYMENT_DETAILS` (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  BILL_ID BIGINT,
  CARD_TYPE VARCHAR(100) DEFAULT NULL,
  CARD_NUMBER INT,
  NO_OF_PRODUCT INT,
  TOTAL_AMOUNT FLOAT,
  PAYMNET_MODE VARCHAR(100) DEFAULT NULL,
  PAYMENT_CASH INT,
  PAYMENT_CHANGE FLOAT,
  GIFT_CARD_NUMBER INT,
  GIFT_CARD_AMOUNT INT,
  EXPIRE_DATE VARCHAR(20) DEFAULT NULL,
  CVV_NUMBER INT,
  COUPON1_AMOUNT INT,
  COUPON2_AMOUNT INT,
  CREATED_DATE DATE,
  CREATED_BY VARCHAR(10),
  UPDATED_DATE DATE,
  UPDATED_BY VARCHAR(10),
  FOREIGN KEY(BILL_ID) REFERENCES `operox`.`BILL`(ID),
  PRIMARY KEY (`ID`) 
); 