

CALL operox.AlterTableAddColumn ('operox','PRODUCT','PRODUCT_ID','VARCHAR(150) NULL AFTER `ID`');

CALL operox.AlterTableAddColumn ('operox','DEPARTMENT','STATUS','INT(10) NULL AFTER `DESCRIPTION`');


DROP TABLE IF EXISTS `operox`.`COUNTER`;
CREATE TABLE `operox`.`COUNTER` (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  COUNTER_NAME VARCHAR(500) DEFAULT NULL,
  COUNTER_TYPE VARCHAR(500) DEFAULT NULL,
  STORE_ID BIGINT,
  DESCRIPTION TEXT DEFAULT NULL,
  STATUS INT,
  CREATED_DATE DATE,
  CREATED_BY VARCHAR(10),
  UPDATED_DATE DATE,
  UPDATED_BY VARCHAR(10),
  FOREIGN KEY(STORE_ID) REFERENCES `operox`.`STORE`(ID),
  PRIMARY KEY (`ID`) 
); 


ALTER TABLE `operox`.`CUSTOMER` 
ADD COLUMN `CUSTOMER_TYPE` VARCHAR(45) NULL AFTER `CUSTOMER_NAME`;

ALTER TABLE `operox`.`CUSTOMER` 
ADD COLUMN `CUSTOMER_TIN` VARCHAR(45) NULL AFTER `STATUS`;

ALTER TABLE `operox`.`CUSTOMER` 
CHANGE COLUMN `CREATED_BY` `CREATED_BY` VARCHAR(45) NULL DEFAULT NULL ;


