INSERT INTO `operox`.`ROLE` (`ID`, `ROLE_NAME`, `DISPLAY_NAME`) VALUES ('6', 'ROLE_PRODUCTION_MANAGER', 'PRODUCTION MANAGER');

CALL operox.AlterTableAddColumn ('operox','WORK_ORDER','PURCHASE_ORDER_ID','VARCHAR(250) NULL AFTER `CUSTOMER_ID`');

CALL operox.AlterTableAddColumn ('operox','BILL_ITEMS','TOTAL_AMOUNT','FLOAT NULL AFTER `PRICE`');