CALL operox.AlterTableAddColumn ('operox','USER','DOJ','DATE NULL AFTER `EMAIL`');
CALL operox.AlterTableAddColumn ('operox','USER','COMPENSATION','VARCHAR(20) NULL AFTER `DOJ`');
CALL operox.AlterTableAddColumn ('operox','USER','USER_IMAGE','MEDIUMBLOB NULL AFTER `COMPENSATION`');
CALL operox.AlterTableAddColumn ('operox','USER','FILE_CONTENT_TYPE','VARCHAR(50) NULL AFTER `USER_IMAGE`');


DROP TABLE IF EXISTS `operox`.`SHIFT`;
CREATE TABLE `operox`.`SHIFT` (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  SHIFT_NAME VARCHAR(500) DEFAULT NULL,
  STORE_ID BIGINT,
  IN_TIME VARCHAR(10),
  OUT_TIME VARCHAR(10),
  DESCRIPTION TEXT DEFAULT NULL,
  STATUS INT,
  CREATED_DATE DATE,
  CREATED_BY VARCHAR(10),
  UPDATED_DATE DATE,
  UPDATED_BY VARCHAR(10),
  FOREIGN KEY(STORE_ID) REFERENCES `operox`.`STORE`(ID),
  PRIMARY KEY (`ID`) 
); 


INSERT INTO `operox`.`SHIFT` (`ID`, `SHIFT_NAME`, `STORE_ID`, `IN_TIME`, `OUT_TIME`, `DESCRIPTION`, `STATUS`) VALUES ('1', 'General Shift', '1', '10:00 AM', '5:00 PM', 'General Shift Timings', '1');

CALL operox.AlterTableAddColumn ('operox','USER','SHIFT_ID','BIGINT NULL AFTER `DEPARTMENT_ID`');
ALTER TABLE `operox`.`USER`  ADD FOREIGN KEY(SHIFT_ID) REFERENCES SHIFT(ID);