UPDATE `operox`.`ROLE` SET `ROLE_NAME`='ROLE_QC_MANAGER', `DISPLAY_NAME`='QC MANAGER' WHERE `ID`='5';
INSERT INTO `operox`.`ROLE` (`ID`, `ROLE_NAME`, `DISPLAY_NAME`) VALUES ('7', 'ROLE_HR_MANAGER', 'HR MANAGER');
